# Generated by Django 5.2.8 on 2025-11-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Caisse')),
            ],
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Mode de paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde initial de caisse')),
                ('annee_analyse', models.IntegerField(verbose_name="Année d'analyse")),
            ],
        ),
        migrations.AlterField(
            model_name='typemouvement',
            name='libelle',
            field=models.CharField(max_length=50, verbose_name='Type de mouvement'),
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateField(verbose_name='Date')),
                ('num_piece', models.CharField(blank=True, max_length=30, null=True, verbose_name='N° pièce')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé / Description')),
                ('entree', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Entrée (Crédit)')),
                ('sortie', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Sortie (Débit)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.caisse', verbose_name='Caisse')),
                ('mode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.modepaiement', verbose_name='Mode de paiement')),
                ('type_mouvement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.typemouvement', verbose_name='Type de mouvement')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['date_mouvement', 'id'],
            },
        ),
    ]
