# Generated by Django 5.2.8 on 2025-11-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_caisse_modepaiement_parametre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisse',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='pieces/%Y/%m', verbose_name='Pièce jointe'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='annee_analyse',
            field=models.IntegerField(blank=True, null=True, verbose_name="Année d'analyse"),
        ),
    ]
